import numpy as np
a = np.arange(7,16,2)
print('a = ', a)
b = np.arange(10,5,-1)
print('b = ', b)
c = np.arange(15,-1,-5)
print('c = ', c)

print('\n')
a = np.linspace(7,15,5)
print('a = ', a)
b = np.linspace(10,6,5)
print('b = ', b)
c = np.linspace(15,0,4)
print('c = ', c)